### ISSUE TITLE
Fibonacci needs optimisation

### ISSUE THREAD

**Issue by Prathamesh404** [Pratik-sys/code-and-learn#5]
- The recursion stack slow the computation for larger numbers.
- Using Dynamic Programming, memoization is expected to reduce the repeated work done by current program.
- Segregate the programs on the basis of time/ space complexity/ Method for execution of program.

**Comment by Pratik-sys** [comment]
ok, i'll check it

**Comment by Pratik-sys** [comment]
I hope so new commit may have fixed the issue.
Thanks
